name: Auto Sync Fork

on:
  schedule:
    - cron: "0 7 * * *"   # 每天自动同步（UTC时间）
  workflow_dispatch:      # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false

      - name: Upstream Sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

          upstream_sync_repo: peiyingyao/Rule-for-OCD
          upstream_sync_branch: master

      - name: Show result
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "Upstream updated"
